@startuml
participant "Tarea Enviar()" as tarea
participant "EnviarTexto()" as enviar
participant "EnviarCaracter()" as caracter
participant "UART2_IRQHandler" as servicio
participant "UART" as uart

[-> tarea: TaskResume(Enviar)
activate tarea
tarea -> enviar: 'Hola'
activate enviar
enviar --> uart: 'H'
activate uart
enviar --> tarea: TRUE
deactivate enviar
[<- tarea: WaitBits(COMPLETO)
deactivate tarea

uart -> servicio: TxEmpty
deactivate uart
activate servicio
servicio -> caracter
activate caracter
caracter --> uart: 'o'
activate uart
caracter --> servicio: FALSE
deactivate caracter
deactivate servicio

uart -> servicio: TxEmpty
deactivate uart
activate servicio
servicio -> caracter
activate caracter
caracter --> uart: 'l'
activate uart
caracter --> servicio: FALSE
deactivate caracter
deactivate servicio

uart -> servicio: TxEmpty
deactivate uart
activate servicio
servicio -> caracter
activate caracter
caracter --> uart: 'a'
activate uart
caracter --> servicio: TRUE
deactivate caracter
servicio -> tarea: SetBits(COMPLETO);
deactivate servicio
deactivate uart
activate tarea
[<- tarea: TaskSuspend()
deactivate tarea
@enduml